name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/docker-build-and-push.yml@main
    secrets: inherit
    with:
      REGISTRY: ghcr
      IMAGE_NAME: my-dotnet-project
      REPOSITORY: haondt
      BUILD_CONTEXT: My-Dotnet-Project
      DOCKERFILE: My-Dotnet-Project/My-Dotnet-Project/Dockerfile