name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/ghcr-build-and-push.yml@main
    secrets: inherit
    with:
      image: my-dotnet-project
      repository: haondt
      context: My-Dotnet-Project
      file: My-Dotnet-Project/My-Dotnet-Project/Dockerfile