on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      BUILD_CONTEXT:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false
  
env:
  IMAGE_FULL_NAME: >-
    ${{ 
      inputs.REGISTRY == 'ghcr' && format('ghcr.io/{0}/{1}', inputs.REPOSITORY, inputs.IMAGE_NAME) || 
      format('{0}/{1}', inputs.REPOSITORY, inputs.IMAGE_NAME) 
    }}
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: >-
          ${{ 
            inputs.REGISTRY == 'ghcr' && 'write' ||
            'read'
          }}
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: >-
          ${{ 
            inputs.REGISTRY == 'ghcr' && 'write' ||
            'none'
          }}

    steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: set up for docker
          uses: ./.github/actions/docker-setup
          
        - name: log into docker-hub
          if: inputs.REGISTRY == 'docker-hub'
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: log into ghcr
          if: inputs.REGISTRY == 'ghcr'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: extract Docker metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.IMAGE_FULL_NAME }}
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}

        - name: Build and push Docker image
          id: build-and-push
          uses: docker/build-push-action@v5
          with:
            context: ${{ inputs.BUILD_CONTEXT }}
            file: ${{ inputs.DOCKERFILE }}
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
        